name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-11-06-i686
        override: true
        default: true
    
    - name: Install i386 deps
      run: |
        sudo dpkg --add-architecture i386 
        sudo apt-get update 
        sudo apt-get install build-essential g++-multilib -y

    - uses: actions/checkout@v2
    - name: Build server plugin
      run: |
        cargo build --package server --release
        strip -s target/release/libserver.so -o stripped.so

    - uses: actions/upload-artifact@v2
      with:
        name: cef-${{ matrix.os }}.so
        path: stripped.so